Add random_gamma to the augmentation functions
deepmind/dm_pix pull request #48
Opened 2022-10-01 12:12 UTC by alonfnt

Since I have several projects where I have used this wrapper, and following on #43, I thought it would be okay to submit it as a PR to have it already in PIX.

`random_gamma` is just a wrapper for `adjust_gamma` where the value of the gamma parameter is sampled uniformly in the given range, similarly to what other augmentation functions already do in the library.

2022-10-03 19:37 UTC, alonfnt commented
Hi @claudiofantacci, sorry for the confusion but apparently my branch was not up to date with upstream.
Now it should have the `reference_fn` argument correctly written and it is passing the test locally :)

2022-10-04 09:22 UTC, claudiofantacci requested changes
Please add an entry for this new function in https://github.com/deepmind/dm_pix/blob/master/docs/api.rst 😄

2022-10-04 09:22 UTC, claudiofantacci commented on dm_pix/__init__.py
> +random_gamma = augment.random_gamma
Please move this after `random_flip_up_down` to keep alphabetical order.

2022-10-04 14:14 UTC, claudiofantacci approved these changes
LGTM, thanks 🚀 
I will take it from here, no need to any other actions 👍

2022-10-04 17:06 UTC, merged